### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by georgiAgi** [johanneshy/labtris#1]
_Ladattu 5. kesäkuuta 16:30._

Tetris-peli näyttää rakentuvan todella tyylikkäästi ja määrätietoisesti. Kehittävää palautetta on aika vaikeaa antaa näin hyvin suunnitellulle projektille!

Joitain kommentteja asioista, jotka pistivät silmään:

**Luokkakaavio**
Luokkakaavio on selkeä kaikkine yhteysmerkintöineen UML-periaatteita noudattaen. Siinä ei kuitenkaan ollut ihan jokaista luokkaa merkitty, ja en esimerkiksi täysin hahmottanut Tetrominos-laatikon merkitystä luokkakaaviossa. Ymmärrän toki, että moni luokista oli sen kaltainen, että lisääminen olisi melko triviaalia. Koodin lukemisen kannalta siitä olisi kuitenkin ollut apua.

**Kommentit**
Suurin osa koodista oli selkeää ja yksinkertaisiin kokonaisuuksiin jaettua, mutta joissain (monimutkaisemmissa) koodinpätkissä pieni selvennys //komenttina vähintäänkin vauhdittaa kanssakoodarin ohjelman lukemista.

**Playfield-luokka**
Playfield-luokan konstruktorien rekursiivisuus hieman hämmensi minua. Myös siinä tapahtuva RandomBagin luominen (joka siis tapahtuu Enumin kautta) herätti kysymyksen. Tavallaan ymmärsin, miksi päädyit luomaan RandomBagin TetrominoTypen kautta, mutta se tuntuu olevan nyt vähän mutkan takana.

**Testit**
Testit näyttävät olevan todella kattavat. Monessa testissä oli monta assertEqualsia, mikä tuntui vähän tarpeettomaltakin (esim. PlayfieldFormatterTest). Toki jos itse pysyt kärryillä, että testit toimivat oikein, niin mikäs siinä. Kommentointi tuskin haittaisi testeissäkään.

**Final-muuttujat**
Käytät paljon final-muuttujia, joista osan ymmärrän, mutta esimerkiksi Position-	luokassa en niitä täysin ymmärtänyt. Eikö paikka kuitenkin muutu pelin edetessä, vai meinaako tämä sitä lopullista paikkaa johon Tetrominot asettuvat. Epäilen, että tässäkin selkeyttävä kommentointi jeesaisi hieman yksinkertaisemman koodaajan ymmärrystä.

Kaiken kaikkiaan koodista saa kuvan, että tekijä tietää mitä tekee. Projekti näyttää todella määrätietoiselta ja tarkkaan harkitulta! Muista vaan myös, että koodissa on kiva olla kommentteja meitä vähän alemman tason koodaajia varten. :) 

Edit: Korjasin hieman Luokkakaavio-kohtaa

**Comment by johanneshy** [comment]
Hyvää palautetta!

Luokkakaavio oli torstain palautuksesta ja sunnuntaihin mennessä koodiin oli tullut muutoksia. Esimerkiksi Tetrominos nimetty kuvaavammin TetrominoType.

Toisiaan kutsuvat konstruktorit ovat tapa määritellä oletusarvot joillekin parametreista. Joissakin ohjelmointikielissä oletusarvot voi antaa metodin määrittelyssä, mutta Javassa tämä pitää tehdä metodin ylikuormituksella (ts. sama metodi eri parametreilla, koskee myös konstruktoria).

Final-muuttujat Cell- ja Position-luokassa tekevät luokkien olioista käytännössä muuttumattomia (immutable). Esimerkiksi paikan vaihtaminen edellyttää uuden olion luontia ja viittauksen päivittämistä paikkaluokkaa käyttävissä olioissa. Toinen vaihtoehto olisi tietenkin suoraan muuttaa paikkaolion tilaa. Final-määreen käytössä on se etu, ettei alkuperäistä oliota pääse vahingossakaan muuttamaan. Olion voi jakaa huoletta esim. käyttöliittymäkerroksen kanssa. Tämä on vähän makuasia ja ei luonnollisestikaan sovellu kaikkiin tarkoituksiin.

Kommentointia on tarkoitus lisätä viimeistään sitä mukaa kuin viikoittaisiin palautuksiin sitä vaaditaan :)
