### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Samppaa** [johanneshy/labtris#2]
- Listenereiden käyttö oivallettu hyvin, mikä tekee systeemistä järkevän. Nyt tarvittaville komponenteille on helppo ilmoittaa pelitilan muutoksesta, ja ne voivat reagoida tarvittavalla tavalla. Itse en ainakaan keksi parempaa tapaa toteuttaa tätä.
- Factoryiden käyttö on myös tajuttu ja se selkeyttää selvästi ohjelman rakennetta. Nyt tetrominot on helppo luoda yhdellä metodilla factory luokasta, ja antaa parametriksi vain tetrominon tyyppi.
- Onko luokka TetrominoFormatter.java välttämättä tarpeellinen? Itse olisin ehkä sisällyttänyt metodit kuten `toString()` ja `toStringOneLiner()` itse tetroninon omaan luokkaan, sillä se olisi tuntunut luontevammalta. Loppupeleissä kyse on mielipiteestä, mutta yleensä javassa `toString()` metodi sisältyy luokkaan itseensä. Staattinen `ParseString()` metodi sopisi myös itse Tetrominon luokkaan.
- Samat kommentit luokalle PlayFieldFormatter.java kuin edellä mainitulle TetrominoFormatter.java luokalle.
- Abstractin komentoluokan(Command.java) käyttö on hyvä ratkaisu, jota en ehkä olisi itse heti keksinyt. Nyt kontrollointi tapahtuu komento-objektien avulla eikä suoraan ohjelman eri osia muuttamalla. Hyvä.
- Edellisessä koodikatselmoinnissa huomautin toista henkilöä, että kannattaa käyttää enumeraatiota, mutta tässä se on oivallettu TetrominoType.java:ssa järkevästi.
- Metodien nimeäminen + muut koodin laatuvaatimukset ovat hyvin kunnossa. Testit ovat myös todella kattavat ja hyvät.
- Javassa on mahdollisuus alustaa muuttujia myös suoraan luontivaiheessa, esim. GameController.java luokassa voisi laittaa `private GameState state = new GameState()`, jolloin tätä ei tarvitse tehdä konstruktorissa. Kyse on taas makuasiasta.
- Yleisesti ottaen koodi on laadultaa niin hyvää, että siitä on hyvin vaikea löytää mitään parantamisenvaraa edellä ilmoittamieni muutama seikan lisäksi.

**Comment by johanneshy** [comment]
Kiitos kommenteista!
